spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springboot
    username: bogarin
    password: bogarin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
